
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devendra
 */
public class AdminStaffReport extends javax.swing.JFrame {

    /**
     * Creates new form AdminStaffReport
     */
    public AdminStaffReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        AC = new javax.swing.JRadioButton();
        dis = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REG. NO", "NAME", "SEX", "CITY", "STATE", "CONTACT", "DATE", "EMAIL", "PASSWORD", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 1180, 124));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1114, 0, -1, 24));

        jButton1.setText("CHANGE / UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 62, 325, -1));

        jButton3.setText("DELETE");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 62, 315, -1));

        jButton4.setText("STAFF DETAILS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 62, 248, -1));

        AC.setBackground(new java.awt.Color(255, 153, 255));
        buttonGroup1.add(AC);
        AC.setText("Active");
        getContentPane().add(AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 62, 60, -1));

        dis.setBackground(new java.awt.Color(255, 102, 255));
        buttonGroup1.add(dis);
        dis.setText("Discharged");
        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });
        getContentPane().add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 62, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/b8.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminDash().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           DefaultTableModel dml =(DefaultTableModel) jTable1.getModel();

        // IF DONOR SELECTED
      if(AC.isSelected())
            
        { //SEARCH where status is discharged
         // String l =DC.getText();
         // System.out.print(l);
            dml.setRowCount(0);
                String sql ="Select * from staffdata where Status = ?";
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                    PreparedStatement stm = con.prepareStatement(sql);
                    stm.setString(1, AC.getText());

                    ResultSet rs = stm.executeQuery();
                    if(rs.next())
                    {    String RNo=(rs.getString("RegNo"));
                        String Name=(rs.getString("Name"));
                        String Sex=(rs.getString("Sex"));

                      

                        String city = (rs.getString("City"));
                        String State=(rs.getString("State"));
                        String contact=(rs.getString("Contact"));
                        String Date=(rs.getString("Date"));
                        String Email=(rs.getString("Email"));
                        String Password=(rs.getString("Password"));
                        String Status=(rs.getString("Status"));

                        dml.addRow(new Object[] {RNo,Name,Sex,city,State,contact,Date,Email,Password,Status});

                        JOptionPane.showMessageDialog(null,"Hi..!! ADMIN"+"\n DETAILS as follows (-:");
                        //Moving to Admin userInterface
                        // this.dispose();
                        //     new AdminDash().setVisible(true);
                        //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );

                    }

                    else{
                        JOptionPane.showMessageDialog(null," NO ACTIVE STAFF ");
                        //JOptionPane.showMessageDialog(null,"Wrong Password or UserID"+user.getText()+"\nRETRY !!"+JOptionPane.ERROR_MESSAGE );
                    }
                }
                catch(ClassNotFoundException | SQLException | HeadlessException f){
                    JOptionPane.showMessageDialog(null,f );

                
            }
            //SEARCH WITH NAME
           
        }
        

        //IF RECIVER SELECTED

        
        
        else 
        if(dis.isSelected())

        { //SEARCH where status is discharged
         // String l =DC.getText();
         // System.out.print(l);
                dml.setRowCount(0);
                String sql ="Select * from staffdata where Status = ?";
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                    PreparedStatement stm = con.prepareStatement(sql);
                    stm.setString(1, dis.getText());

                    ResultSet rs = stm.executeQuery();
                    if(rs.next())
                    {    String RNo=(rs.getString("RegNo"));
                        String Name=(rs.getString("Name"));
                        String Sex=(rs.getString("Sex"));

                      

                        String city = (rs.getString("City"));
                        String State=(rs.getString("State"));
                        String contact=(rs.getString("Contact"));
                        String Date=(rs.getString("Date"));
                        String Email=(rs.getString("Email"));
                        String Password=(rs.getString("Password"));
                        String Status=(rs.getString("Status"));

                        dml.addRow(new Object[] {RNo,Name,Sex,city,State,contact,Date,Email,Password,Status});

                        JOptionPane.showMessageDialog(null,"Hi..!! ADMIN"+"\n Details as follows,,, (-:");
                        //Moving to Admin userInterface
                        // this.dispose();
                        //     new AdminDash().setVisible(true);
                        //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );

                    }

                    else{
                        JOptionPane.showMessageDialog(null," RETRY !!");
                        //JOptionPane.showMessageDialog(null,"Wrong Password or UserID"+user.getText()+"\nRETRY !!"+JOptionPane.ERROR_MESSAGE );
                    }
                }
                catch(ClassNotFoundException | SQLException | HeadlessException f){
                    JOptionPane.showMessageDialog(null,f );

                
            }
            //SEARCH WITH NAME
           
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStaffReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStaffReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStaffReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStaffReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStaffReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AC;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
