
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devendra
 */
public class AdminStaffUPDATE extends javax.swing.JFrame {

    /**
     * Creates new form AdminStaffUPDATE
     */
    public AdminStaffUPDATE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DELETE = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        regn = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        contact = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pwd = new javax.swing.JTextField();
        Active = new javax.swing.JLabel();
        Discharged = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, 71, 31));

        jLabel2.setText("CITY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 158, 60, 28));

        city.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFocusGained(evt);
            }
        });
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 162, 155, -1));

        jLabel4.setText("STATE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 192, 116, 31));

        jLabel5.setText("CONTACT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 229, -1, 20));

        DELETE.setText("Delete DATA ");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        getContentPane().add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 374, -1, -1));

        jLabel6.setText("SEX");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, 83, 30));

        jLabel7.setText("REG NO.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 59, 71, 20));

        regn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnActionPerformed(evt);
            }
        });
        getContentPane().add(regn, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 56, 65, -1));

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 56, -1, -1));

        UPDATE.setText("Update DATA");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 374, -1, -1));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 229, 166, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 90, 196, -1));
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 127, 196, -1));
        getContentPane().add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 197, 155, -1));

        jLabel8.setText("DATE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 48, 25));

        jLabel9.setText("EMAIL");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 296, 48, 24));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 262, 166, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 298, 166, -1));

        jLabel10.setText("PASSWORD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 331, 72, 25));
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 333, 166, -1));

        Active.setText("Active");
        getContentPane().add(Active, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 436, 79, 25));

        Discharged.setText("Discharged");
        getContentPane().add(Discharged, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 436, 68, 25));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 0, -1, 24));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/b9.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        String k =regn.getText();
        String j=Discharged.getText();
        
         String SQL = "update staffdata set Status ='"+j+"' where RegNo='"+k+"' " ;
        try{
            
           Class.forName("com.mysql.jdbc.Driver");
                        Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                        PreparedStatement smt=cn.prepareStatement(SQL);
                        smt.executeUpdate(SQL);
                        cn.close(); 
               JOptionPane.showMessageDialog(null,"Here You Go...ADMIN "+"\n STAFF Data DELETED  Sucessfully !!");
              
        }
        catch(ClassNotFoundException | SQLException | HeadlessException z)
        {
            JOptionPane.showMessageDialog(null,z );
            System.out.println(z);

        }
    }//GEN-LAST:event_DELETEActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
        int k =Integer.parseInt(regn.getText());
        String a = regn.getText();
        String b = name.getText();
        String c=sex.getText();
        String d=city.getText();
        String e=state.getText();
        String f =contact.getText();
        String g =date.getText();
        String h =email.getText();
        String i =pwd.getText();
        String j=Active.getText();
        
         String SQL = "update staffdata set RegNo ='"+a+"' , Name ='"+b+"' , Sex ='"+c+"' ,City ='"+d+"' ,State ='"+e+"' ,Contact ='"+f+"' ,Date ='"+g+"' ,EMail ='"+h+"' , Password ='"+i+"', Status ='"+j+"' where RegNo='"+k+"' " ;
        try{
            
           Class.forName("com.mysql.jdbc.Driver");
                        Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                        PreparedStatement smt=cn.prepareStatement(SQL);
                        smt.executeUpdate(SQL);
                        cn.close(); 
               
              JOptionPane.showMessageDialog(null,"Here You Go...ADMIN "+"\n STAFF Data UPDATED  Sucessfully !!");
        }
        catch(ClassNotFoundException | SQLException | HeadlessException z)
        {
            JOptionPane.showMessageDialog(null,z );
            System.out.println(z);

        }
        

        
        
        // add current date
       // Calendar currentDate = Calendar.getInstance();
        //SimpleDateFormat formatter= new SimpleDateFormat("dd/MM/yyyy");
        //String t = formatter.format(currentDate.getTime());
        //lbl3.setText(t);
    }//GEN-LAST:event_UPDATEActionPerformed

    private void cityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFocusGained
        // TODO add your handling code here:

        // WRITE A QUARRY WITH LABEL8 'S REGISTRATION NUMBER TO DRAW NAME AND BLOOD GROUP FROM DONORSDATA TABLE
    }//GEN-LAST:event_cityFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql ="Select * from staffdata where RegNo = ?";
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1, regn.getText());
            ResultSet rs = stm.executeQuery();
            if( rs.next() )
            {
                String m=rs.getString("Name");                name.setText(m+"");
                String n=rs.getString("Sex");                 sex.setText(""+n);
                String o=rs.getString("City");                city.setText(""+o);
                String p=rs.getString("State");               state.setText(""+p);
                String q=rs.getString("Contact");             contact.setText(""+q);
                String r=rs.getString("Date");                date.setText(""+r);
                String s=rs.getString("EMail");               email.setText(""+s);
                String t=rs.getString("Password");            pwd.setText(""+t);
                
               
                JOptionPane.showMessageDialog(null,"Here You Go...ADMIN "+"\n SEARCHED data fetched  Sucessfully !!");
                //Moving to Admin userInterface

                //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );

            }

            else{
                JOptionPane.showMessageDialog(null,"Data Not Found "+"\n RETRY !!");
                //JOptionPane.showMessageDialog(null,"Wrong Password or UserID"+user.getText()+"\nRETRY !!"+JOptionPane.ERROR_MESSAGE );
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException f){
            JOptionPane.showMessageDialog(null,f );

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void regnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminStaffReport().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStaffUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStaffUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStaffUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStaffUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStaffUPDATE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Active;
    private javax.swing.JButton DELETE;
    private javax.swing.JLabel Discharged;
    private javax.swing.JButton UPDATE;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField date;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pwd;
    private javax.swing.JTextField regn;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField state;
    // End of variables declaration//GEN-END:variables
}
