
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form userReg
     */
    public UserRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pW = new javax.swing.JPasswordField();
        rePw = new javax.swing.JPasswordField();
        mail = new javax.swing.JTextField();
        dt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        state = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        regNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(422, 500));
        setSize(new java.awt.Dimension(390, 460));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 10, 59, 23);

        jButton2.setText("RESET");
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 420, 63, 23);

        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 420, 81, 23);

        jLabel3.setText("RE-ENTER PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 370, 109, 14);

        jLabel2.setText("CHOOSE PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 340, 102, 20);
        getContentPane().add(pW);
        pW.setBounds(150, 340, 159, 20);
        getContentPane().add(rePw);
        rePw.setBounds(150, 370, 159, 20);

        mail.setToolTipText("Enter a Valid E-mail");
        getContentPane().add(mail);
        mail.setBounds(150, 310, 217, 21);
        getContentPane().add(dt);
        dt.setBounds(150, 280, 240, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 280, 57, 22);

        jLabel1.setText("E-mail");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 310, 40, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Mobile");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 250, 48, 23);
        getContentPane().add(contact);
        contact.setBounds(150, 250, 186, 23);

        jLabel5.setText("STATE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 57, 20);

        state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M.P.", "U.P.", "U.K." }));
        getContentPane().add(state);
        state.setBounds(150, 170, 186, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("City");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 140, 39, 20);

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        getContentPane().add(city);
        city.setBounds(150, 140, 186, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Sex");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 110, 37, 20);

        sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", " " }));
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });
        getContentPane().add(sex);
        sex.setBounds(150, 110, 80, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("ENTER FULL NAME");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 70, 94, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(150, 80, 238, 20);

        jLabel9.setText("REGISTRATION NUMBER");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 40, 130, 30);
        getContentPane().add(regNo);
        regNo.setBounds(150, 50, 107, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/b2.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 390, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
                String r=regNo.getText();
                String a=name.getText();
                String b=sex.getSelectedItem().toString();
       //get current date time with Calendar()
       
                String c=city.getText();
                String d=state.getSelectedItem().toString();
                String e=contact.getText();
                String f=dt.getText();
                String g=mail.getText();
                String h = pW.getText();
                String i = rePw.getPassword().toString();
                
     //  System.out.println("t1 "+a+" t2 "+b+" t3 "+c+" t4 "+d+" t5 "+e+" t6 "+f+" t7 "+g+" t8 "+h+" t9 "+i);
             
           try{
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                        PreparedStatement smt=cn.prepareStatement("insert into staffdata values(?,?,?,?,?,?,?,?,?)");
                        smt.setString(1,r);
                        smt.setString(2,a);
                        smt.setString(3,b);
                        smt.setString(4,c);
                        smt.setString(5,d);
                        smt.setString(6,e);
                        smt.setString(7,f);
                        smt.setString(8,g);
                        smt.setString(9,h);
                        smt.executeUpdate();
                        cn.close();     

           
                            JOptionPane.showMessageDialog(this,"Data Inserted","Success",JOptionPane.PLAIN_MESSAGE);
                            int j = Integer.parseInt(regNo.getText());
                            j=j+1;
                            regNo.setText(""+j);
                            this.dispose();
                           new LogIn().setVisible(true);
                 }
            catch(Exception err)
        {
                             System.out.println("Opps ErroRRR !! :"+err);
        }
     
                //}
              //  else
             //   {
                
             //   System.out.println("Entered password does not matches !! Please re-enter");
                
              //  String k = pW.setText("");
                //String m = rePw.setText("");
                
            //    }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
                     Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter= new SimpleDateFormat("dd/MM/yyyy  HH:mm:ss");
        String t = formatter.format(currentDate.getTime());
        dt.setText(t);
        
         String sql ="Select count(RegNo) from staffdata";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
            PreparedStatement stm = con.prepareStatement(sql);
            //stm.setString(1, regn.getText());
            ResultSet rs = stm.executeQuery();
            if(rs.next())
            {
                String m=rs.getString("count(RegNo)");
                
                
                
               int k=Integer.parseInt(m);
               k=k+1;
                
               regNo.setText(k+"");
                JOptionPane.showMessageDialog(null,"ALL SET... "+"\n New Registration!!");
                //Moving to Admin userInterface

                //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );

            }

            else{
                JOptionPane.showMessageDialog(null,"Data Not Found "+"\n RETRY !!");
                //JOptionPane.showMessageDialog(null,"Wrong Password or UserID"+user.getText()+"\nRETRY !!"+JOptionPane.ERROR_MESSAGE );
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException f){
            JOptionPane.showMessageDialog(null,f );

        }

        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField dt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pW;
    private javax.swing.JPasswordField rePw;
    private javax.swing.JTextField regNo;
    private javax.swing.JComboBox sex;
    private javax.swing.JComboBox state;
    // End of variables declaration//GEN-END:variables
}
