
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class UXbuyerReg extends javax.swing.JFrame {

    /**
     * Creates new form UXsoldUnit
     */
    public UXbuyerReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        reg = new javax.swing.JTextField();
        dt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ref = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ct = new javax.swing.JTextField();
        stte = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BUYER'S DETAIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 235, 42));

        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 115, 88, -1));
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 206, 166, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Donor Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 115, -1, -1));

        jButton4.setText("RESET");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 284, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 115, 180, -1));

        jButton1.setText("SAVE TO DB");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 284, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 50, 20));

        tt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ttAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 162, 166, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("REFERAL/REMARK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 259, 113, 42));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Mobile");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 153, 50, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Reg./Donor No");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 83, 21));
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 153, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("Time");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, 83, 20));

        ref.setColumns(20);
        ref.setRows(5);
        jScrollPane1.setViewportView(ref);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 259, -1, 61));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        jLabel2.setText("City");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 191, 50, -1));

        jLabel3.setText("State");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 226, -1, -1));

        ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctActionPerformed(evt);
            }
        });
        getContentPane().add(ct, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 185, 180, -1));

        stte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MP", "UP", "UK", "BR", "HR" }));
        getContentPane().add(stte, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 223, 180, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/b133.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a=reg.getText();
        String b=name.getText();
        String c=contact.getText();
        String d=ct.getText();
        String e=stte.getSelectedItem().toString();
        String f=tt.getText();
        String g=dt.getText();
        String h=ref.getText();
        

        //  System.out.println("t1 "+a+" t2 "+b+" t3 "+c+" t4 "+d+" t5 "+e+" t6 "+f+" t7 "+g+" t8 "+h+" t9 "+i);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
            PreparedStatement smt=cn.prepareStatement("insert into reciverdata values(?,?,?,?,?,?,?,?)");
            smt.setString(1,a);
            smt.setString(2,b);
            smt.setString(3,c);
            smt.setString(4,d);
            smt.setString(5,e);
            smt.setString(6,f);
            smt.setString(7,g);   
            smt.setString(8,h);
            smt.executeUpdate();
            cn.close();
            JOptionPane.showMessageDialog(this,"RECIVER Data Inserted","Success",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            new UXbyrQuant().setVisible(true);
        }
        catch(HeadlessException | ClassNotFoundException | SQLException err)
        {
            System.out.println("Opps ErroRRR !! :"+err);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        
          
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter= new SimpleDateFormat("dd/MM/yyyy");
        String t = formatter.format(currentDate.getTime());
        dt.setText(t);
  

    }//GEN-LAST:event_formWindowGainedFocus

    private void ttAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ttAncestorAdded
        // TODO add your handling code here:
          
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter= new SimpleDateFormat("HH:mm:ss");
        String t = formatter.format(currentDate.getTime());
        tt.setText(t);
    }//GEN-LAST:event_ttAncestorAdded

    private void ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new StaffUserdash().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                        
           String sql ="Select count(RegNo) from reciverdata";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
            PreparedStatement stm = con.prepareStatement(sql);
            //stm.setString(1, regn.getText());
            ResultSet rs = stm.executeQuery();
            if(rs.next())
            {
                String m=rs.getString("count(RegNo)");
                
                
                
               int k=Integer.parseInt(m);
               k=k+1;
                
               reg.setText(k+"");
                JOptionPane.showMessageDialog(null,"ALL SET... "+"\n New Registration!!");
                //Moving to Admin userInterface

                //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );

            }

            else{
                JOptionPane.showMessageDialog(null,"Data Not Found "+"\n RETRY !!");
                //JOptionPane.showMessageDialog(null,"Wrong Password or UserID"+user.getText()+"\nRETRY !!"+JOptionPane.ERROR_MESSAGE );
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException f){
            JOptionPane.showMessageDialog(null,f );

        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UXbuyerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UXbuyerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UXbuyerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UXbuyerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UXbuyerReg().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact;
    private javax.swing.JTextField ct;
    private javax.swing.JTextField dt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextArea ref;
    private javax.swing.JTextField reg;
    private javax.swing.JComboBox stte;
    private javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables
}
