
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devendra
 */
public class UXbyrQuant extends javax.swing.JFrame {

    /**
     * Creates new form UXbyrQuant
     */
    public UXbyrQuant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pint = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        regn = new javax.swing.JTextField();
        bg = new javax.swing.JComboBox();
        stck = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("SAVE to packet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 336, -1, -1));

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        getContentPane().add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 85, -1, -1));

        jLabel6.setText("BLOOD GROUP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 83, 30));

        jLabel7.setText("REG NO.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 71, 27));

        jButton4.setText("Update Date");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 336, -1, -1));

        jButton3.setText("BACK TO DASHBOARD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 257, 176, 31));

        jLabel1.setText("USER NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 71, 31));

        jLabel2.setText("QUANTITY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, 60, 28));

        pint.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pintFocusGained(evt);
            }
        });
        getContentPane().add(pint, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 211, 70, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("UNITS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel4.setText("DATE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 257, 116, 31));
        getContentPane().add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 124, 179, 27));

        regn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnActionPerformed(evt);
            }
        });
        getContentPane().add(regn, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 86, 65, 27));

        bg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "B+", "O-", "O+", "B-", "AB+", "AB-" }));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 163, 68, 30));

        stck.setText("STOCK");
        stck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stckActionPerformed(evt);
            }
        });
        getContentPane().add(stck, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 370, -1, -1));

        status.setText("Recived");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 370, -1, 23));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/b5.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String a = regn.getText();
        String b = nm.getText();
        String c = bg.getSelectedItem().toString();
        String d = pint.getText();
        String e = dt.getText();
      

        //SAVE ABOVE ENTERED DATA INTO PACKETS TABLE

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
            PreparedStatement smt=cn.prepareStatement("insert into rcvrpackets values(?,?,?,?,?)");
           
            smt.setString(1,a);
            smt.setString(2,b);
            smt.setString(3,c);
            smt.setString(4,d);
            smt.setString(5,e);
            

            smt.executeUpdate();
       
            cn.close();

            //into Packet details
            JOptionPane.showMessageDialog(this,"Data Updated. ","Success",JOptionPane.PLAIN_MESSAGE);
            stck.doClick();

        }
        catch(HeadlessException | ClassNotFoundException | SQLException err)
        {
            System.out.println("Opps ErroRRR !! :"+err);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
        String sql ="Select * from reciverdata where RegNo = ?";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1, regn.getText());
            ResultSet rs = stm.executeQuery();
            if(rs.next())
            {
                String m=rs.getString("Name");
                nm.setText(m+"");
                
                String o=rs.getString("Date");
                dt.setText(""+o);
                
               
                JOptionPane.showMessageDialog(null,"Here You Go... "+"\n Your data fetched  Sucessfully !!");
                //Moving to Admin userInterface

                //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );

            }

            else{
                JOptionPane.showMessageDialog(null,"Data Not Found "+"\n RETRY !!");
                //JOptionPane.showMessageDialog(null,"Wrong Password or UserID"+user.getText()+"\nRETRY !!"+JOptionPane.ERROR_MESSAGE );
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException f){
            JOptionPane.showMessageDialog(null,f );

        }

    }//GEN-LAST:event_SEARCHActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        // add current date
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter= new SimpleDateFormat("dd/MM/yyyy");
        String t = formatter.format(currentDate.getTime());
        dt.setText(t);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void pintFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pintFocusGained
        // TODO add your handling code here:

        // WRITE A QUARRY WITH LABEL8 'S REGISTRATION NUMBER TO DRAW NAME AND BLOOD GROUP FROM DONORSDATA TABLE

    }//GEN-LAST:event_pintFocusGained

    private void regnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnActionPerformed

    private void stckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stckActionPerformed
        // TODO add your handling code here:
                         String q=bg.getSelectedItem().toString();
                         String r=pint.getText();
                         String s=dt.getText();
                         String t=status.getText();
                        
        
        //SAVE ABOVE ENTERED DATA INTO PACKETS TABLE
        
     try{
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                        PreparedStatement smt=cn.prepareStatement("insert into stocks values(?,?,?,?)");
                        smt.setString(1,q);
                        smt.setString(2,r);
                        smt.setString(3,s);
                        smt.setString(4,t);
                    
                        smt.executeUpdate();
                        cn.close();     

           
                            JOptionPane.showMessageDialog(this,"Data Updated into Stock !!","Success",JOptionPane.PLAIN_MESSAGE);
                            
                 }
            catch(HeadlessException | ClassNotFoundException | SQLException err)
        {
                             System.out.println("Opps ErroRRR !! :"+err);
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_stckActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new StaffUserdash().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UXbyrQuant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UXbyrQuant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UXbyrQuant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UXbyrQuant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UXbyrQuant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SEARCH;
    private javax.swing.JComboBox bg;
    private javax.swing.JLabel dt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nm;
    private javax.swing.JTextField pint;
    private javax.swing.JTextField regn;
    private javax.swing.JLabel status;
    private javax.swing.JButton stck;
    // End of variables declaration//GEN-END:variables
}
