
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class UXdonorQuantProfile extends javax.swing.JFrame {

    /**
     * Creates new form UXdonorProfile
     */
    public UXdonorQuantProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pint = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        regn = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        ND = new javax.swing.JTextField();
        Stock = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("USER NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 71, 31));

        jLabel2.setText("QUANTITY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, 60, 28));

        pint.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pintFocusGained(evt);
            }
        });
        getContentPane().add(pint, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 207, 47, 28));

        jLabel3.setText("UNITS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 221, -1, -1));

        jLabel4.setText("DATE OF DONATION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, 116, 31));

        jLabel5.setText("NEXT DATE OF DONATION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 283, -1, 39));

        jButton1.setText("SAVE to packet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 340, -1, -1));

        jLabel6.setText("BLOOD GROUP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, 83, 30));

        jLabel7.setText("REG NO.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, 71, 27));
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 112, 179, 27));
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 161, 178, 26));

        regn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnActionPerformed(evt);
            }
        });
        getContentPane().add(regn, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 74, 65, 27));

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 74, -1, -1));

        jButton3.setText("BACK TO DASHBOARD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 0, -1, -1));
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 246, 176, 31));

        ND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NDActionPerformed(evt);
            }
        });
        getContentPane().add(ND, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 287, 166, 31));

        Stock.setText("Save to stock");
        Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockActionPerformed(evt);
            }
        });
        getContentPane().add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 381, 0, -1));

        status.setText("Donated");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 390, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/b10.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    
        
                         String a = regn.getText();
                         String b = lbl1.getText();
                         String c=lbl2.getText();
                         String d=pint.getText();
                         String e=lbl3.getText();
                         String f =ND.getText();
        
        //SAVE ABOVE ENTERED DATA INTO PACKETS TABLE
        
     try{
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                        PreparedStatement smt=cn.prepareStatement("insert into dnrpackets values(?,?,?,?,?,?)");
                        String SQ = "update donorsdata set Date ='"+e+"' , NextDate ='"+f+"'where RegNo='"+a+"' " ; 
                        smt.setString(1,a);
                        smt.setString(2,b);
                        smt.setString(3,c);
                        smt.setString(4,d);
                        smt.setString(5,e);
                        smt.setString(6,f);
                    
                        smt.executeUpdate();
                        smt.executeUpdate(SQ);
                        cn.close();     

           //into Packet details
                            JOptionPane.showMessageDialog(this,"Data Updated. ","Success",JOptionPane.PLAIN_MESSAGE);
                            Stock.doClick();
                            
                 }
            catch(HeadlessException | ClassNotFoundException | SQLException err)
        {
                             System.out.println("Opps ErroRRR !! :"+err);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        
      
 

        
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void pintFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pintFocusGained
        // TODO add your handling code here:
        
        // WRITE A QUARRY WITH LABEL8 'S REGISTRATION NUMBER TO DRAW NAME AND BLOOD GROUP FROM DONORSDATA TABLE
        
    }//GEN-LAST:event_pintFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                    String sql ="Select * from donorsdata where RegNo = ?";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1, regn.getText());
            ResultSet rs = stm.executeQuery();
                  if(rs.next())
                     {
                         String m=rs.getString("Name");
                         lbl1.setText(m+"");
                         String n=rs.getString("BloodGroup");
                         lbl2.setText(""+n);
                         String o=rs.getString("Date");
                         lbl3.setText(""+o);
                         String p=rs.getString("NextDate");
                         ND.setText(""+p);
                          JOptionPane.showMessageDialog(null,"Here You Go... "+lbl1.getText()+" "+"\n Your data fetched  Sucessfully !!");
//Moving to Admin userInterface
                                
                //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );
                
                         }

                    else{
                             JOptionPane.showMessageDialog(null,"Data Not Found "+"\n RETRY !!");
                               //JOptionPane.showMessageDialog(null,"Wrong Password or UserID"+user.getText()+"\nRETRY !!"+JOptionPane.ERROR_MESSAGE );
                            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException f){
            JOptionPane.showMessageDialog(null,f );

        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void regnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnActionPerformed

    private void NDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NDActionPerformed

    private void StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockActionPerformed
        // TODO add your handling code here:
        //save blood group and quantity 
                         
                         String q=lbl2.getText();
                         String r=pint.getText();
                         String s=lbl3.getText();
                         String t=status.getText();
                         
                        
        
        //SAVE ABOVE ENTERED DATA INTO PACKETS TABLE
        
     try{
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                        PreparedStatement smt=cn.prepareStatement("insert into stocks values(?,?,?,?)");
                        smt.setString(1,q);
                        smt.setString(2,r);
                        smt.setString(3,s);
                        smt.setString(4,t);
                        
                    
                        smt.executeUpdate();
                        cn.close();     

           
                            JOptionPane.showMessageDialog(this,"Data Updated into Stock !!","Success",JOptionPane.PLAIN_MESSAGE);
                            
                 }
            catch(HeadlessException | ClassNotFoundException | SQLException err)
        {
                             System.out.println("Opps ErroRRR !! :"+err);
        }
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_StockActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new StaffUserdash().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UXdonorQuantProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UXdonorQuantProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UXdonorQuantProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UXdonorQuantProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UXdonorQuantProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ND;
    private javax.swing.JButton Stock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JTextField pint;
    private javax.swing.JTextField regn;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
