
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class UXNewDonor extends javax.swing.JFrame {

    /**
     * Creates new form newDonor
     */
    public UXNewDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JComboBox();
        city = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        sex = new javax.swing.JComboBox();
        dt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reg = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nxtDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SAVE ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 100, -1));

        bg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB", "O", " " }));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 51, -1));

        city.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 70, 30));

        stt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(stt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 163, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("City");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 50, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Mobile");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Age");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 39, 20));

        contact.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, -1));

        age.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 39, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Sex");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 37, 20));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 80, -1));

        sex.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", " " }));
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 71, 30));

        dt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 163, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Donor Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 20));

        jButton4.setBackground(new java.awt.Color(0, 153, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("RESET");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 100, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Donor Detail Form");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 197, 46));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Reg./Donor No");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 21));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("State");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Blood Group");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        reg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 80, -1));

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("NEXT APPOINTMENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 120, 30));

        nxtDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nxtDate.setToolTipText("DD/MM/YYYY");
        nxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtDateActionPerformed(evt);
            }
        });
        getContentPane().add(nxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 163, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("** NEXT DATE OF BLOOD DONATION IS ALWAYS AFTER 90 DAYS OF DONATING BLOOD FOR SAFETY HEALTH REASONS.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 690, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/B6.JPG"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 770));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                String a=reg.getText();
                String b=name.getText();
                String c=bg.getSelectedItem().toString();
                String d=sex.getSelectedItem().toString();
       //get current date time with Calendar()
       
                String e=age.getText();
                //9int values only excepted
                
                String g=city.getText();
                String h=stt.getText();
                String i=dt.getText();
                String f=contact.getText();
                String j=nxtDate.getText();

     //  System.out.println("t1 "+a+" t2 "+b+" t3 "+c+" t4 "+d+" t5 "+e+" t6 "+f+" t7 "+g+" t8 "+h+" t9 "+i);
           try{
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                        PreparedStatement smt=cn.prepareStatement("insert into donorsdata values(?,?,?,?,?,?,?,?,?,?)");
                        smt.setString(1,a);
                        smt.setString(2,b);
                        smt.setString(3,c);
                        smt.setString(4,d);
                        smt.setString(5,e);
                        smt.setString(6,g);
                        smt.setString(7,h);
                        smt.setString(8,i);
                        smt.setString(9,f);
                        smt.setString(10,j);
                        




                        smt.executeUpdate();
                        cn.close();     

           
                            JOptionPane.showMessageDialog(this,"Data Inserted","Success",JOptionPane.PLAIN_MESSAGE);
                            //MOVE TO donor's profile to add about the quantity of the blood he wants to donate and shows next date of donation
                            this.dispose();
                            new UXdonorQuantProfile().setVisible(true);
                 }
            catch(HeadlessException | ClassNotFoundException | SQLException err)
        {
                             System.out.println("Opps ErroRRR !! :"+err);
        }
     

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //first oo =new first();
       // oo.setVisible(true);
      //  this.dispose();
        
        this.dispose();
        new StaffUserdash().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
            // Date date = new Date();
    //    dt.setText(date.toString());
        
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter= new SimpleDateFormat("dd/MM/yyyy  HH:mm:ss");
        String t = formatter.format(currentDate.getTime());
        dt.setText(t);
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                String sql ="Select * from donorsdata where RegNo = ?";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1, reg.getText());
            ResultSet rs = stm.executeQuery();
                  if(rs.next())
                     {
                         String m=rs.getString("Name");
                         name.setText(m+"");
                         String n=rs.getString("BloodGroup");
                         bg.getEditor().setItem(""+n);
                         String q=rs.getString("Sex");
                         sex.getEditor().setItem(""+q);
                         String o=rs.getString("Date");
                        dt.setText(""+o);
                         String p=rs.getString("NextDate");
                         nxtDate.setText(""+p);
                          JOptionPane.showMessageDialog(null,"Here You Go...  "+"\n Your data fetched  Sucessfully !!");
//Moving to Admin userInterface
                                
                //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );
                
                         }

                    else{
                             JOptionPane.showMessageDialog(null,"Data Not Found "+"\n RETRY !!");
                               //JOptionPane.showMessageDialog(null,"Wrong Password or UserID"+user.getText()+"\nRETRY !!"+JOptionPane.ERROR_MESSAGE );
                            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException f){
            JOptionPane.showMessageDialog(null,f );

        }
        
        
        //This will search and get details of a donor from DONORSDATA table 
                    

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          
           String sql ="Select count(RegNo) from donorsdata";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
            PreparedStatement stm = con.prepareStatement(sql);
            //stm.setString(1, regn.getText());
            ResultSet rs = stm.executeQuery();
            if(rs.next())
            {
                String m=rs.getString("count(RegNo)");
                
                
                
               int k=Integer.parseInt(m);
               k=k+1;
                
               reg.setText(k+"");
                JOptionPane.showMessageDialog(null,"ALL SET... "+"\n New Registration!!");
                //Moving to Admin userInterface

                //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );

            }

            else{
                JOptionPane.showMessageDialog(null,"Data Not Found "+"\n RETRY !!");
                //JOptionPane.showMessageDialog(null,"Wrong Password or UserID"+user.getText()+"\nRETRY !!"+JOptionPane.ERROR_MESSAGE );
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException f){
            JOptionPane.showMessageDialog(null,f );

        }

        
        
          
          
          
          
          
          
          
        
        // here this will count the numbers of donors from the table and provide the new registration number to this frame
        
    }//GEN-LAST:event_formWindowOpened

    private void nxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nxtDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UXNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UXNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UXNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UXNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UXNewDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JComboBox bg;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField dt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nxtDate;
    private javax.swing.JTextField reg;
    private javax.swing.JComboBox sex;
    private javax.swing.JTextField stt;
    // End of variables declaration//GEN-END:variables
}
