
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devendra
 */
public class UXrecordDR extends javax.swing.JFrame {

    /**
     * Creates new form UXrecordDR
     */
    public UXrecordDR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rcr = new javax.swing.JRadioButton();
        SEARCHbtn = new javax.swing.JButton();
        dnr = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REG. NO", "NAME", "BLOOD GROUP", "SEX", "AGE", "CITY", "STATE", "CONTACT", "DATE", "NEXT DATE / REMARK"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 1300, 134));

        rcr.setBackground(new java.awt.Color(255, 153, 255));
        buttonGroup1.add(rcr);
        rcr.setText("RECIVER/BUYER");
        getContentPane().add(rcr, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        SEARCHbtn.setBackground(new java.awt.Color(255, 51, 255));
        SEARCHbtn.setText("SEARCH");
        SEARCHbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHbtnActionPerformed(evt);
            }
        });
        getContentPane().add(SEARCHbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 228, -1));

        dnr.setBackground(new java.awt.Color(255, 102, 255));
        buttonGroup1.add(dnr);
        dnr.setText("DONOR");
        dnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnrActionPerformed(evt);
            }
        });
        getContentPane().add(dnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 105, -1));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/b8.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SEARCHbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHbtnActionPerformed
        DefaultTableModel dml =(DefaultTableModel) jTable1.getModel();

        // IF DONOR SELECTED
        if (dnr.isSelected())
        { //to view fresh data in table
            dml.setRowCount(0);
            //SEARCH WITH Contact NUMBER

            String sql ="Select * from donorsdata";
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                PreparedStatement stm = con.prepareStatement(sql);
                ResultSet rs = stm.executeQuery();
                if(rs.next())
                {
                        String RNo=(rs.getString("RegNo"));
                        String Name=(rs.getString("Name"));
                        String Sex=(rs.getString("Sex"));
                        String BG=(rs.getString("BloodGroup"));
                        String AG=(rs.getString("Age"));

                        String city = (rs.getString("City"));
                        String State=(rs.getString("State"));
                        String contact=(rs.getString("Contact"));
                        String Date=(rs.getString("Date"));
                        String NextDate=(rs.getString("NextDate"));
                        

                        dml.addRow(new Object[] {RNo,Name,BG,Sex,AG,city,State,contact,Date,NextDate});

                    JOptionPane.showMessageDialog(null,"Hi..!! Admin "+"\n Details as follows,,, (-:");
                    //Moving to Admin userInterface
                    // this.dispose();
                    //     new AdminDash().setVisible(true);
                    //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );

                }

            }
            catch(ClassNotFoundException | SQLException | HeadlessException z){
                JOptionPane.showMessageDialog(null,z );

            }
        }

        //IF RECIVER SELECTED

        else
        if(rcr.isSelected())

        { //SEARCH WITH REGISTRATION NUMBER
            dml.setRowCount(0);
            String sql ="Select * from reciverdata";
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/bloodbank","root","tiger");
                PreparedStatement stm = con.prepareStatement(sql);
                ResultSet rs = stm.executeQuery();
                if(rs.next())
                {
                     String RNo=(rs.getString("RegNo"));
                     String Name=(rs.getString("Name"));
                        String Sex="N/A";
                        String BG="N/A";
                        String AG="N/A";

                     String city = (rs.getString("City"));
                     String State=(rs.getString("State"));
                     String contact=(rs.getString("Contact"));
                     String Date=(rs.getString("Date"));
                     String Rm=(rs.getString("Remark"));
                    // String NextDate=(rs.getString("NextDate"));

                     dml.addRow(new Object[] {RNo,Name,BG,Sex,AG,city,State,contact,Date,Rm});

                    JOptionPane.showMessageDialog(null,"Hi..!! Admin "+"\n Details as follows,,, (-:");
                    //Moving to Admin userInterface
                    // this.dispose();
                    //     new AdminDash().setVisible(true);
                    //JOptionPane.showMessageDialog(null,"Welcome"+user.getText()+"\nYou are LogedIn Sucessfully !!"+JOptionPane.PLAIN_MESSAGE );

                }

            }
            catch(ClassNotFoundException | SQLException | HeadlessException z){
                JOptionPane.showMessageDialog(null,z );

            }
        }

    }//GEN-LAST:event_SEARCHbtnActionPerformed

    private void dnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnrActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminDash().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UXrecordDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UXrecordDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UXrecordDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UXrecordDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UXrecordDR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SEARCHbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dnr;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rcr;
    // End of variables declaration//GEN-END:variables
}
